CREATE TABLE PRAYER
(
    id VARCHAR(128) PRIMARY KEY NOT NULL,
    version NUMERIC NOT NULL
);

CREATE TABLE PRAYER_DETAILS
(
    prayer_id VARCHAR(128) REFERENCES PRAYER(id),
    language VARCHAR(20) NOT NULL,
    title VARCHAR(128) NOT NULL,
    content  TEXT NOT NULL,
    version NUMERIC NOT NULL,
    PRIMARY KEY (prayer_id, language)
);

INSERT INTO PRAYER VALUES(1,1);
INSERT INTO PRAYER_DETAILS VALUES(1,'PL','Tytul','Tresc',1);
INSERT INTO PRAYER_DETAILS VALUES(1,'EN','Title','Content',1);