CREATE TABLE CITY
(
    id VARCHAR(128) PRIMARY KEY NOT NULL,
    name VARCHAR(128) NOT NULL,
    version NUMERIC NOT NULL
);

INSERT INTO CITY VALUES(1,'Chęciny',1);
INSERT INTO CITY VALUES(2,'Kielce',1);