CREATE TABLE PHONE
(
  PHO_VERSION NUMERIC NOT NULL DEFAULT 0,
  PHO_ID VARCHAR(128) NOT NULL,
  PHO_NUMBER VARCHAR(20) NOT NULL,
  PRIMARY KEY (PHO_ID)
);


CREATE TABLE PHONE_OWNER
(
  PHR_VERSION NUMERIC NOT NULL,
  PHR_ID VARCHAR(128) REFERENCES PHONE (PHO_ID),
  PHR_LANGUAGE VARCHAR(20) NOT NULL,
  PHR_CONTENT VARCHAR(256) NOT NULL,
  PRIMARY KEY (PHR_ID, PHR_LANGUAGE)
);

CREATE TABLE PHONE_DESCRIPTION
(
  PHD_VERSION NUMERIC NOT NULL,
  PHD_ID VARCHAR(128) REFERENCES PHONE (PHO_ID),
  PHD_LANGUAGE VARCHAR(20) NOT NULL,
  PHD_CONTENT VARCHAR(256) NOT NULL,
  PRIMARY KEY (PHD_ID, PHD_LANGUAGE)
);



CREATE TABLE CITY_PHONE
(
  CPH_CITY VARCHAR(128)  NOT NULL,
  CPH_PHONE VARCHAR(128) NOT NULL,
  PRIMARY KEY (CPH_CITY, CPH_PHONE),
  FOREIGN KEY (CPH_CITY) REFERENCES CITY (ID),
  FOREIGN KEY (CPH_PHONE) REFERENCES PHONE (PHO_ID)
);