CREATE TABLE VERSION
(
  VERSION_TABLE VARCHAR(128)  NOT NULL,
  VERSION_VALUE NUMERIC NOT NULL,
  PRIMARY KEY (VERSION_TABLE)
);

INSERT INTO VERSION (VERSION_TABLE, VERSION_VALUE) VALUES ('USERS', 0);
INSERT INTO VERSION (VERSION_TABLE, VERSION_VALUE) VALUES ('CITIES', 0);
INSERT INTO VERSION (VERSION_TABLE, VERSION_VALUE) VALUES ('NEWS', 0);
INSERT INTO VERSION (VERSION_TABLE, VERSION_VALUE) VALUES ('PHONES', 0);
INSERT INTO VERSION (VERSION_TABLE, VERSION_VALUE) VALUES ('PRAYERS', 0);
INSERT INTO VERSION (VERSION_TABLE, VERSION_VALUE) VALUES ('POI_CATEGORY', 0);
INSERT INTO VERSION (VERSION_TABLE, VERSION_VALUE) VALUES ('POI', 0);
INSERT INTO VERSION (VERSION_TABLE, VERSION_VALUE) VALUES ('SCHEDULER', 0);
