DROP TABLE PHONE_DESCRIPTION;
DROP TABLE PHONE_OWNER;

CREATE TABLE PHONE_DETAILS
(
  PHD_VERSION NUMERIC NOT NULL,
  PHD_ID VARCHAR(128) REFERENCES PHONE (PHO_ID),
  PHD_LANGUAGE VARCHAR(20) NOT NULL,
  PHD_OWNER VARCHAR(256) NOT NULL,
  PHD_DESCRIPTION VARCHAR(256) NOT NULL,
  PRIMARY KEY (PHD_ID, PHD_LANGUAGE)
);

