DELETE FROM VERSION;

INSERT INTO VERSION (VERSION_TABLE, VERSION_VALUE) VALUES ('CITIES', 0);
INSERT INTO VERSION (VERSION_TABLE, VERSION_VALUE) VALUES ('NEWS', 0);
INSERT INTO VERSION (VERSION_TABLE, VERSION_VALUE) VALUES ('PHONES', 0);
INSERT INTO VERSION (VERSION_TABLE, VERSION_VALUE) VALUES ('PRAYERS', 0);
INSERT INTO VERSION (VERSION_TABLE, VERSION_VALUE) VALUES ('POI_CATEGORY', 0);
INSERT INTO VERSION (VERSION_TABLE, VERSION_VALUE) VALUES ('POI', 0);
INSERT INTO VERSION (VERSION_TABLE, VERSION_VALUE) VALUES ('SCHEDULER', 0);
